### ISSUE TITLE
Add more information about database connection in Backend documentation

### ISSUE THREAD

**Issue by pranav-027** [PritamSalunkhe1/Jijau-School-Erp-Admin#1]
On a local setup when one starts the backend server it throws an error 

```
NOT CONNECTED TO NETWORK MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at _createMongoClient (~\Jijau-School-Erp-Admin\backend\node_modules\mongoose\lib\connection.js:768:11)
    at NativeConnection.openUri (~\Jijau-School-Erp-Admin\backend\node_modules\mongoose\lib\connection.js:705:29)
    at Mongoose.connect (~\Jijau-School-Erp-Admin\backend\node_modules\mongoose\lib\index.js:406:15)
```
Adding more information about database connection might help

**Comment by PritamSalunkhe1** [comment]
you need to setup up your mongodb uri in .env file.
